### ISSUE TITLE
have you ever tried to use this for regression?

### ISSUE THREAD

**Issue by Christian-lyc** [bymavis/CAS_ICLR2021#1]
Hi, thank you for your nice work. I used this for the nature dataset, not on the adversarial examples. It worked well. But I'm wondering how about transfering this to regression network. I did some trials, but didn't work well. Do you have some experiences? Looking forward to your relpy. Thank you so much

**Comment by bymavis** [comment]
Hi Yichao,

Thanks for your interest on our work first. I have been a bit busy and have not logged in this project in last few months. Is there still any problem now? And what do you mean by transferring this to regression network? I think CAS could help achieve a better feature extractor in one network, so it should make sense in the regression network. (But the suppressing operation might should be adjusted according to a typical task, for example, we use the CE loss to design CAS loss in the classification network.) If you still have any questions, please feel easy to connect me.

Best,
Yang
