### ISSUE TITLE
checkpoints of pretrained model

### ISSUE THREAD

**Issue by amirhamidihd** [bymavis/CAS_ICLR2021#3]
could you please upload the pre-trained model of CAS on resnet50?

**Comment by bymavis** [comment]
Thanks for your interest. In our paper, we have not evaluated CAS on ResNet-50. But the CAS module should be inserted into ResNet-50 and refer to ResNet-18. (I suggest on the last layer before FC.) If you have more questions, please feel easy to connect me.

**Comment by amirhamidihd** [comment]
Thanks for your reply.
